name: Question / Support
description: Ask a question or request help
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context (optional)
      description: Any relevant details, logs, or attempts so far
